export const appSettings = {
  VERSION_NUMBER: 2.0,
  SENTRY_DSN_URL: '{{SENTRY_DSN_URL}}',
  BUILD_NUMBER: 38,
  SENTRY_AUTH_TOKEN: '{{SENTRY_AUTH_TOKEN}}',
  REVENUE_CAT_APPLE_API_KEY: '{{REVENUE_CAT_APPLE_API_KEY}}',
  REVENUE_CAT_GOOGLE_API_KEY: '{{REVENUE_CAT_GOOGLE_API_KEY}}',
};