export const storageKeys = {
  SNIPPET: 'SNIPPET_',
  CREDENTIALS: 'CREDENTIALS',
  APPEARANCE_MODE: 'APPEARANCE_MODE',
  THEME_ID: 'THEME_ID',
  MILESTONE_NUMBER: 'MILESTONE_NUMBER',
  LAST_REVIEW_PROMPT_DATE: 'LAST_REVIEW_PROMPT_DATE',
  IS_FEATURE_ALERT_DISMISSED: 'IS_FEATURE_ALERT_DISMISSED_',
  LANGUAGE: 'LANGUAGE',
}