export const storageKeys = {
  SNIPPET: 'SNIPPET_',
  CREDENTIALS: 'CREDENTIALS',
  THEME_ID: 'THEME_ID',
  MILESTONE_NUMBER: 'MILESTONE_NUMBER',
  LAST_REVIEW_PROMPT_DATE: 'LAST_REVIEW_PROMPT_DATE',
}