import { colors } from "./colors";

export const themes = {
  'rainbow-light': {
    name: 'Rainbow (light)',
    colors: {
      0: colors.white,
      1: [colors.orange, colors.darkOrange],
      2: [colors.darkBlue, colors.blue],
      3: [colors.red, colors.lightRed],
      4: [colors.green, colors.lightGreen],
      5: [colors.darkYellow, colors.yellow],
      6: [colors.purple, colors.lightPurple],
      100: colors.orange,
      background1: colors.white,
      background2: colors.white,
      'screenHeader1.foreground': colors.gray,
      'screenHeader1.background': colors.darkGray,
      'listHeader1.foreground': colors.mediumGray,
      'listHeader1.background': colors.gray,
      'content1.foreground': colors.white,
      'content1.background': colors.white,
      'content2.foreground': colors.mediumGray,
      'content2.background': colors.snowflake,
      'textInput1.foreground': colors.mediumGray,
      'textInput1.background': colors.whiteGray,
      'textInput2.foreground': colors.mediumGray,
      'textInput2.background': colors.yellow,
      'textInput3.foreground': colors.mediumGray,
      'textInput3.background': colors.snowflake,
      'textArea1.foreground': colors.mediumGray,
      'textArea1.background': colors.white,
      'button1.foreground': colors.gray,
      'button1.background': colors.mediumGray,
      'button2.foreground': colors.mediumGray,
      'button2.background': colors.lightGreen,
      'button3.foreground': colors.mediumGray,
      'button3.background': colors.darkBlue,
      'button4.foreground': colors.mediumGray,
      'button4.background': colors.gray,
    },
    opacities: {
      'content1.text2': .80,
    }
  },
  'rainbow-dark': {
    name: 'Rainbow (dark)',
    colors: {
      0: colors.white,
      1: [colors.orange, colors.darkOrange],
      2: [colors.darkBlue, colors.blue],
      3: [colors.red, colors.lightRed],
      4: [colors.green, colors.lightGreen],
      5: [colors.darkYellow, colors.yellow],
      6: [colors.purple, colors.lightPurple],
      100: colors.orange,
      background1: colors.black,
      background2: colors.black,
      'screenHeader1.foreground': colors.gray,
      'screenHeader1.background': colors.darkGray,
      'listHeader1.foreground': colors.gray,
      'listHeader1.background': colors.gray,
      'content1.foreground': colors.darkGray,
      'content1.background': colors.darkGray,
      'content2.foreground': colors.gray,
      'content2.background': colors.darkGray,
      'textInput1.foreground': colors.gray,
      'textInput1.background': colors.darkGray,
      'textInput2.foreground': colors.darkGray,
      'textInput2.background': colors.yellow,
      'textInput3.foreground': colors.gray,
      'textInput3.background': colors.darkGray,
      'textArea1.foreground': colors.gray,
      'textArea1.background': colors.black,
      'button1.foreground': colors.gray, 
      'button1.background': colors.black,
      'button2.foreground': colors.darkGray, 
      'button2.background': colors.lightGreen,
      'button3.foreground': colors.darkGray, 
      'button3.background': colors.darkBlue,
      'button4.foreground': colors.darkGray, 
      'button4.background': colors.gray,
    },
    opacities: {
      'content1.text2': .80,
    }
  },
  'orange-light': {
    name: 'Orange (light)',
    colors: {
      0: colors.white,
      1: colors.orange1,
      2: colors.orange2,
      3: colors.orange3,
      4: colors.orange4,
      5: colors.orange5,
      6: colors.orange6,
      100: colors.orange1,
      background1: colors.snowflake,
      background2: colors.white,
      'screenHeader1.foreground': colors.gray,
      'screenHeader1.background': colors.darkGray,
      'listHeader1.foreground': colors.mediumGray,
      'listHeader1.background': colors.gray,
      'content1.foreground': colors.mediumGray,
      'content1.background': colors.white,
      'content2.foreground': colors.mediumGray,
      'content2.background': colors.white,
      'textInput1.foreground': colors.mediumGray,
      'textInput1.background': colors.white,
      'textInput2.foreground': colors.mediumGray,
      'textInput2.background': colors.white,
      'textInput3.foreground': colors.mediumGray,
      'textInput3.background': colors.snowflake,
      'textArea1.foreground': colors.mediumGray,
      'textArea1.background': colors.white,
      'button1.foreground': colors.gray,
      'button1.background': colors.mediumGray,
      'button2.foreground': colors.mediumGray,
      'button2.background': colors.orange1,
      'button3.foreground': colors.mediumGray,
      'button3.background': colors.orange3,
      'button4.foreground': colors.mediumGray,
      'button4.background': colors.snowflake,
    },
    opacities: {
      'content1.text2': 0.75,
    }
  },
  'orange-dark': {
    name: 'Orange (dark)',
    colors: {
      0: colors.gray,
      1: colors.orange1,
      2: colors.orange2,
      3: colors.orange3,
      4: colors.orange4,
      5: colors.orange5,
      6: colors.orange6,
      100: colors.orange1,
      background1: colors.black,
      background2: colors.black,
      'screenHeader1.foreground': colors.gray,
      'screenHeader1.background': colors.darkGray,
      'listHeader1.foreground': colors.gray,
      'listHeader1.background': colors.gray,
      'content1.foreground': colors.black,
      'content1.background': colors.darkGray,
      'content2.foreground': colors.gray,
      'content2.background': colors.darkGray,
      'textInput1.foreground': colors.gray,
      'textInput1.background': colors.darkGray,
      'textInput2.foreground': colors.darkGray,
      'textInput2.background': colors.gray,
      'textInput3.foreground': colors.gray,
      'textInput3.background': colors.mediumGray,
      'textArea1.foreground': colors.gray,
      'textArea1.background': colors.black,
      'button1.foreground': colors.gray, 
      'button1.background': colors.black,
      'button2.foreground': colors.darkGray, 
      'button2.background': colors.orange1,
      'button3.foreground': colors.darkGray, 
      'button3.background': colors.orange3,
      'button4.foreground': colors.darkGray, 
      'button4.background': colors.gray,
    },
    opacities: {
      'content1.text2': 0.50
    }
  },
  'stone': {
    name: 'Stone',
    colors: {
      0: colors.white,
      1: colors.silver1,
      2: colors.silver2,
      3: colors.silver3,
      4: colors.silver4,
      5: colors.silver5,
      6: colors.silver6,
      100: colors.silver1,
      background1: colors.silver1,
      background2: colors.white,
      'screenHeader1.foreground': colors.silver3,
      'screenHeader1.background': colors.darkGray,
      'listHeader1.foreground': colors.mediumGray,
      'listHeader1.background': colors.silver3,
      'content1.foreground': colors.mediumGray,
      'content1.background': colors.white,
      'content2.foreground': colors.mediumGray,
      'content2.background': colors.silver6,
      'textInput1.foreground': colors.mediumGray,
      'textInput1.background': colors.whiteGray,
      'textInput2.foreground': colors.mediumGray,
      'textInput2.background': colors.whiteGray,
      'textInput3.foreground': colors.mediumGray,
      'textInput3.background': colors.whiteGray,
      'textArea1.foreground': colors.mediumGray,
      'textArea1.background': colors.white,
      'button1.foreground': colors.silver3,
      'button1.background': colors.mediumGray,
      'button2.foreground': colors.mediumGray,
      'button2.background': colors.silver2,
      'button3.foreground': colors.mediumGray,
      'button3.background': colors.silver4,
      'button4.foreground': colors.mediumGray,
      'button4.background': colors.silver1,
    },
    opacities: {
      'content1.text2': 1,
    }
  },
  'beach-sunset': {
    name: 'Beach Sunset',
    colors: {
      0: colors.white,
      1: colors.sunset,
      2: colors.burntSienna,
      3: colors.cambridgeBlue,
      4: colors.lightDelftBlue,
      5: colors.eggshell,
      6: colors.lightSunset,
      100: colors.delftBlue,
      background1: colors.lightSunset,
      background2: colors.whiteSunset,
      'screenHeader1.foreground': colors.delftBlue,
      'screenHeader1.background': colors.sunset,
      'listHeader1.foreground': colors.delftBlue,
      'listHeader1.background': colors.whiteSunset,
      'content1.foreground': colors.delftBlue,
      'content1.background': colors.whiteSunset,
      'content2.foreground': colors.delftBlue,
      'content2.background': colors.whiteSunset,
      'textInput1.foreground': colors.delftBlue,
      'textInput1.background': colors.whiteSunset,
      'textInput2.foreground': colors.delftBlue,
      'textInput2.background': colors.whiteSunset,
      'textInput3.foreground': colors.delftBlue,
      'textInput3.background': colors.lightSunset,
      'textArea1.foreground': colors.delftBlue,
      'textArea1.background': colors.whiteSunset,
      'button1.foreground': colors.sunset, 
      'button1.background': colors.delftBlue,
      'button2.foreground': colors.delftBlue,
      'button2.background': colors.cambridgeBlue,
      'button3.foreground': colors.sunset,
      'button3.background': colors.delftBlue,
      'button4.foreground': colors.delftBlue,
      'button4.background': colors.lightSunset,
    },
    opacities: {
      'content1.text2': 1
    }
  }
};