import { colors } from "./colors";

export const themes = {
  'default-light': {
    name: 'Snippeta Light',
    colors: {
      0: colors.white,
      1: colors.lightYellow,
      2: colors.lightBlue,
      3: colors.lightRed,
      4: colors.lightGreen,
      5: colors.lightPurple,
      6: colors.lightGray,
      100: colors.nebulaBlue,
      background1: colors.gray,
      background2: colors.white,
      'screenHeader1.foreground': colors.white,
      'screenHeader1.background': colors.darkGray,
      'listHeader1.foreground': colors.darkGray,
      'listHeader1.background': colors.gray,
      'content1.foreground': colors.darkGray,
      'content1.background': colors.white,
      'textInput1.foreground': colors.darkGray,
      'textInput1.background': colors.whiteGray,
      'textInput2.foreground': colors.darkGray,
      'textInput2.background': colors.lightYellow,
      'textInput3.foreground': colors.darkGray,
      'textInput3.background': colors.whiteGray,
      'textArea1.foreground': colors.darkGray,
      'textArea1.background': colors.white,
      'button1.foreground': colors.darkGray, 
      'button1.background': colors.nebulaBlue,
      'button2.foreground': colors.darkGray, 
      'button2.background': colors.lightGreen,
      'button3.foreground': colors.darkGray, 
      'button3.background': colors.lightBlue,
      'button4.foreground': colors.darkGray, 
      'button4.background': colors.gray,
    }
  },
  'default-dark': {
    name: 'Snippeta Dark',
    colors: {
      0: colors.gray,
      1: colors.lightYellow,
      2: colors.lightBlue,
      3: colors.lightRed,
      4: colors.lightGreen,
      5: colors.lightPurple,
      6: colors.lightGray,
      100: colors.nebulaBlue,
      background1: colors.black,
      background2: colors.black,
      'screenHeader1.foreground': colors.gray,
      'screenHeader1.background': colors.darkGray,
      'listHeader1.foreground': colors.gray,
      'listHeader1.background': colors.gray,
      'content1.foreground': colors.gray,
      'content1.background': colors.darkGray,
      'textInput1.foreground': colors.gray,
      'textInput1.background': colors.darkGray,
      'textInput2.foreground': colors.darkGray,
      'textInput2.background': colors.lightYellow,
      'textInput3.foreground': colors.darkGray,
      'textInput3.background': colors.whiteGray,
      'textArea1.foreground': colors.gray,
      'textArea1.background': colors.black,
      'button1.foreground': colors.darkGray, 
      'button1.background': colors.nebulaBlue,
      'button2.foreground': colors.darkGray, 
      'button2.background': colors.lightGreen,
      'button3.foreground': colors.darkGray, 
      'button3.background': colors.lightBlue,
      'button4.foreground': colors.darkGray, 
      'button4.background': colors.gray,
    }
  },
  'beach-sunset': {
    name: 'Beach Sunset',
    colors: {
      0: colors.white,
      1: colors.delftBlue,
      2: colors.burntSienna,
      3: colors.sunset,
      4: colors.cambridgeBlue,
      5: colors.eggshell,
      6: colors.lightSunset,
      100: colors.delftBlue,
      background1: colors.lightSunset,
      background2: colors.whiteSunset,
      'screenHeader1.foreground': colors.delftBlue,
      'screenHeader1.background': colors.sunset,
      'listHeader1.foreground': colors.delftBlue,
      'listHeader1.background': colors.whiteSunset,
      'content1.foreground': colors.delftBlue,
      'content1.background': colors.whiteSunset,
      'textInput1.foreground': colors.delftBlue,
      'textInput1.background': colors.whiteSunset,
      'textInput2.foreground': colors.delftBlue,
      'textInput2.background': colors.whiteSunset,
      'textInput3.foreground': colors.delftBlue,
      'textInput3.background': colors.whiteSunset,
      'textArea1.foreground': colors.delftBlue,
      'textArea1.background': colors.whiteSunset,
      'button1.foreground': colors.sunset, 
      'button1.background': colors.delftBlue,
      'button2.foreground': colors.delftBlue,
      'button2.background': colors.cambridgeBlue,
      'button3.foreground': colors.sunset,
      'button3.background': colors.delftBlue,
      'button4.foreground': colors.delftBlue,
      'button4.background': colors.lightSunset,
    }
  }
};